#!/usr/bin/env node
/**
 * gen-guide.mjs — refreshes the AUTOGENERATED methods table in GUIDE.md.
 *
 * The list of tools is DERIVED FROM SOURCE: we read src/server.ts to see which
 * `register*Tools(...)` helpers are actually wired up, resolve each to its source
 * file, and parse the `server.registerTool("name", { title, description })` calls.
 * That means adding/removing/renaming a tool changes this output — and the CI
 * `--check` will fail until GUIDE.md is regenerated.
 *
 * Only the block between the AUTOGEN markers is rewritten. The plain-Russian
 * intro and examples above the markers are hand-written and never touched.
 *
 * Usage:
 *   node scripts/gen-guide.mjs           # write GUIDE.md in place
 *   node scripts/gen-guide.mjs --check   # exit 1 if GUIDE.md is stale
 *
 * No external dependencies (Node built-ins only).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SRC = join(ROOT, "src");
const GUIDE = join(ROOT, "GUIDE.md");

const BEGIN = "<!-- AUTOGEN:METHODS:BEGIN -->";
const END = "<!-- AUTOGEN:METHODS:END -->";

// --- 1. Discover the registration modules actually used by server.ts ---------

/** Returns [{ fn, file }] for every register*Tools helper called in server.ts. */
function discoverToolModules() {
  const serverSrc = readFileSync(join(SRC, "server.ts"), "utf8");

  // Map every imported register*Tools identifier to its module path.
  const fnToPath = new Map();
  const importRe = /import\s*(?:type\s*)?\{([^}]*)\}\s*from\s*["']([^"']+)["']/g;
  let m;
  while ((m = importRe.exec(serverSrc))) {
    const path = m[2];
    for (const raw of m[1].split(",")) {
      const name = raw.trim().split(/\s+as\s+/)[0].trim();
      if (/^register\w*Tools$/.test(name)) fnToPath.set(name, path);
    }
  }

  // Keep only those actually invoked, in call order.
  const modules = [];
  const seen = new Set();
  const callRe = /\b(register\w*Tools)\s*\(/g;
  while ((m = callRe.exec(serverSrc))) {
    const fn = m[1];
    if (fnToPath.has(fn) && !seen.has(fn)) {
      seen.add(fn);
      const rel = fnToPath.get(fn).replace(/\.js$/, ".ts");
      modules.push({ fn, file: resolve(SRC, rel) });
    }
  }
  return modules;
}

// --- 2. Parse registerTool() calls out of a source file ----------------------

/** Extracts the balanced {...} object literal that starts at/after `from`. */
function objectLiteralAt(src, from) {
  const start = src.indexOf("{", from);
  if (start < 0) return "";
  let depth = 0;
  for (let i = start; i < src.length; i++) {
    const c = src[i];
    if (c === "{") depth++;
    else if (c === "}" && --depth === 0) return src.slice(start, i + 1);
  }
  return src.slice(start);
}

/** Reads title/description string(s) for a config-object key. */
function readField(obj, key) {
  const idx = obj.indexOf(`${key}:`);
  if (idx < 0) return "";
  const after = obj.slice(idx + key.length + 1);
  // stop before the next known key so we don't bleed into other fields
  const stop = after.search(/\n\s*(?:title|description|inputSchema|annotations)\s*:/);
  const scope = stop >= 0 ? after.slice(0, stop) : after;
  let out = "";
  for (const s of scope.matchAll(/"((?:[^"\\]|\\.)*)"/g)) out += s[1];
  return out.replace(/\\"/g, '"').trim();
}

function parseTools(file) {
  const src = readFileSync(file, "utf8");
  const tools = [];
  const re = /server\.registerTool\(\s*["']([^"']+)["']\s*,/g;
  let m;
  while ((m = re.exec(src))) {
    const obj = objectLiteralAt(src, m.index);
    tools.push({
      name: m[1],
      title: readField(obj, "title"),
      description: readField(obj, "description"),
    });
  }
  return tools;
}

// --- 3. Curated plain-Russian gloss, keyed by tool name ----------------------
// Source is the authority for WHICH tools exist; this dictionary supplies the
// obyvatel-friendly wording. A tool present in source but missing here still
// renders (falls back to its English title) so --check always reflects reality.

const GROUPS = [
  {
    title: "Находим и смотрим таблицы",
    tools: {
      sheets_list: ["Показывает список ваших таблиц (можно по части названия).", "«Найди таблицу „Бюджет“»"],
      sheets_get_info: ["Показывает название таблицы и список её листов/вкладок.", "«Какие вкладки есть в этой таблице?»"],
      sheets_read_range: ["Читает значения из ячеек (диапазон, например A1:C10).", "«Покажи данные из первого листа»"],
      sheets_find: ["Ищет текст в таблице, ничего не меняя.", "«Найди в таблице строку с Ивановым»"],
      sheets_get_formatting: ["Показывает оформление ячеек (цвет, шрифт, формат чисел).", "«Какого цвета залита эта ячейка?»"],
    },
  },
  {
    title: "Создаём и наполняем",
    tools: {
      sheets_create: ["Создаёт новую таблицу.", "«Создай таблицу „Учёт расходов“»"],
      sheets_add_tab: ["Добавляет в таблицу новую вкладку/лист.", "«Добавь вкладку „Январь“»"],
      sheets_write_range: ["Записывает/перезаписывает значения в ячейки.", "«Впиши эти суммы в столбец B»"],
      sheets_append_rows: ["Дописывает новые строки в конец данных.", "«Добавь эту строку в конец таблицы»"],
    },
  },
  {
    title: "Чистим и заменяем",
    tools: {
      sheets_clear_range: ["Очищает значения в ячейках (оформление остаётся).", "«Очисти данные в столбце C»"],
      sheets_find_replace: ["Находит и заменяет текст в таблице.", "«Замени везде „шт.“ на „штук“»"],
    },
  },
  {
    title: "Оформление",
    tools: {
      sheets_format_range: ["Оформляет ячейки: жирный, размер, цвет текста и заливки, выравнивание.", "«Сделай шапку жирной и залей серым»"],
      sheets_raw_batch_update: ["Продвинутое: сложное оформление и структура напрямую.", "(для сложных случаев)"],
    },
  },
  {
    title: "Журнал разбора почты",
    tools: {
      triage_log_add: ["Служебное: добавляет запись в журнал разбора писем.", "(используется автоматически)"],
      triage_log_update: ["Служебное: обновляет запись в журнале разбора писем.", "(используется автоматически)"],
      triage_log_get_pending: ["Служебное: показывает незакрытые записи журнала разбора.", "(используется автоматически)"],
    },
  },
  {
    title: "Аккаунты",
    tools: {
      list_accounts: ["Показывает, какие Google-аккаунты подключены.", "«Какие аккаунты подключены?»"],
    },
  },
];

// --- 4. Render the table -----------------------------------------------------

function esc(s) {
  return String(s).replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();
}

function render(allTools) {
  const known = new Map(allTools.map((t) => [t.name, t]));
  const placed = new Set();
  const lines = [];
  lines.push(`_Автоматически сгенерировано из кода (${allTools.length} инструмент(ов)). Не редактируйте вручную — правьте \`scripts/gen-guide.mjs\`._`);
  lines.push("");

  for (const group of GROUPS) {
    const rows = [];
    for (const [name, gloss] of Object.entries(group.tools)) {
      if (!known.has(name)) continue; // tool removed from source → drop the row
      placed.add(name);
      rows.push(`| \`${name}\` | ${esc(gloss[0])} | ${esc(gloss[1])} |`);
    }
    if (!rows.length) continue;
    lines.push(`### ${group.title}`);
    lines.push("");
    lines.push("| Инструмент | Что делает | Пример запроса |");
    lines.push("| --- | --- | --- |");
    lines.push(...rows);
    lines.push("");
  }

  // Any tool in source but not in the curated groups: list it so the guide
  // never silently omits a real capability.
  const leftovers = allTools.filter((t) => !placed.has(t.name));
  if (leftovers.length) {
    lines.push("### Прочее");
    lines.push("");
    lines.push("| Инструмент | Что делает | Пример запроса |");
    lines.push("| --- | --- | --- |");
    for (const t of leftovers) {
      lines.push(`| \`${t.name}\` | ${esc(t.title || t.description || "—")} | — |`);
    }
    lines.push("");
  }
  return lines.join("\n").trimEnd();
}

// --- 5. Splice into GUIDE.md -------------------------------------------------

function build() {
  const modules = discoverToolModules();
  const all = [];
  for (const mod of modules) all.push(...parseTools(mod.file));
  // de-dup by name, keep first occurrence
  const seen = new Set();
  const tools = all.filter((t) => (seen.has(t.name) ? false : seen.add(t.name)));
  return render(tools);
}

function splice(existing, section) {
  const b = existing.indexOf(BEGIN);
  const e = existing.indexOf(END);
  if (b < 0 || e < 0 || e < b) {
    throw new Error(`GUIDE.md is missing the AUTOGEN markers (${BEGIN} … ${END}).`);
  }
  return existing.slice(0, b + BEGIN.length) + "\n\n" + section + "\n\n" + existing.slice(e);
}

function main() {
  const check = process.argv.includes("--check");
  const section = build();
  const existing = readFileSync(GUIDE, "utf8");
  const next = splice(existing, section);
  if (check) {
    if (next !== existing) {
      console.error("GUIDE.md is out of date. Run:  node scripts/gen-guide.mjs");
      process.exit(1);
    }
    console.log("GUIDE.md is up to date.");
    return;
  }
  if (next !== existing) {
    writeFileSync(GUIDE, next);
    console.log("GUIDE.md regenerated.");
  } else {
    console.log("GUIDE.md already up to date.");
  }
}

main();
